### ISSUE TITLE
syn2 release?

### ISSUE THREAD

**Issue by extrawurst** [yanganto/struct-patch#19]
struct-patch is not the only one but one of the last two `gitui` dependencies that keeps me from upgrading :)

**Comment by yanganto** [comment]
Already release in `0.3.0`

**Comment by extrawurst** [comment]
hm ok its actually more complicated. your dependency on `proc-macro-error` will still keep pulling `syn1`: https://gitlab.com/CreepySkeleton/proc-macro-error/-/merge_requests/36

**Comment by extrawurst** [comment]
the crate seems unmaintained. Is there a way to implement `struct-patch-derive` without it?

**Comment by yanganto** [comment]
I will try to fix it this weekend :smile:

**Comment by yanganto** [comment]
And need another weekend, but I will not leave it alone.
