### ISSUE TITLE
support adding additional annotations to the Path structs

### ISSUE THREAD

**Issue by amircodota** [yanganto/struct-patch#24]
We currently have #{patch_derive] which allows adding derive macros to the generated patch structs.

It would be nice to add additional attributes (not sure I'm using the right term here :-)).

For example, it would be nice to add the `serde_with` crate annotations to both generated Patch structs or the struct fields.

**Comment by yanganto** [comment]
Could you give a short code snippets here?  That will be easier to help you.

**Comment by amircodota** [comment]
```
#[derive(Patch, Debug)]
#[patch_derive(Serialize, Deserialize, Default)]
struct Data {
    value: String,
    num: usize,
}
```

This will generate

```
#[derive(Serialize, Deserialize, Default)]
struct PatchData {
  value: Option<String>,
  num: Option<usize>,
}
```

But I would like to have some way to specify that it should be generated with additional macro attributes

```
#[derive(Serialize, Deserialize, Default)]
#[skip_serializing_none]
struct PatchData {
  value: Option<String>,
  num: Option<usize>,
}
```

where the `skip_serializing_none` macro comes from the `serde_with` crate.

Maybe have a `#[patch_attribute]` that's similar to `#[patch_derive]`

```
use serde_with::skip_serializing_none;

#[derive(Patch, Debug)]
#[patch_derive(Serialize, Deserialize, Default)]
#[patch_attribute(skip_serializing_none)]
struct Data {
    value: String,
    num: usize,
}

```

Ideally I could apply this macro to both the struct and its fields

**Comment by yanganto** [comment]
Hi @amircodota,

Thanks for the code snippets, I tried, but there seems to be some restriction. 
I am not sure it is possible to do it. 
It is sorry I can not provide this quickly, please kindly understand.

**Comment by amircodota** [comment]
np :+1: 

Thanks for trying

**Comment by taorepoara** [comment]
I think that a good solution to add behaviors with global `patch` attribute that can be [parsed to a struct](https://github.com/serde-rs/serde/blob/master/serde_derive/src/internals/ast.rs#L66), just like it's [done in serde](https://github.com/serde-rs/serde/blob/28a092261b1b47726c4c16fd00aa7de8df19785f/serde_derive/src/de.rs#L17C22-L17C31). This could ease the implementation of new features and the add of new attributes.
