### ISSUE TITLE
Recursive patch

### ISSUE THREAD

**Issue by JonasFocke01** [yanganto/struct-patch#64]
First of all, this project is amazing, and i use it in my apps on multiple occursions.

One thing im missing, is the option to apply this recursively. 
Having a nested struct will loose data, even if the parent struct is protected via patch.

Initializing the Structs from the JSON
```rust
#![derive(patch)]
struct A {
    foo: usize,
    bar: B,
}

struct B {
    baz: usize,
    foof: usize
}
```
```json
{
    "A": {
        "foo": 0,
        "bar": "B" {
            "baz": "0",
            "foof": 0
        }
    }
}
```
Will loose foof, because B is invalid because of the string in baz.
        
(Sry for invalid syntax, im on mobile)

**Comment by yanganto** [comment]
The example is modified. 
If this still unclear for you or not solve your question, please reopen the issue.
